### ISSUE TITLE
隐藏指定标的

### ISSUE THREAD

**Issue by zhuxujiee** [jinbeizeng/cowpro#3]
标的ID2838、2837、2836三个标的状态改为隐藏，以实现在首页标的列表、我要投资列表不显示这3个标的、已投资该标的在个人中心依然可以看到该标的。

**Comment by mafeng117** [comment]
隐藏指定标的 @jinbeizeng/team

**Comment by zhuxujiee** [comment]
@jinbeizeng/team

**Comment by abigbug** [comment]
已经修改了“首页标的列表、我要投资”这两个 views，增加了 “已发布” 的过滤选项。
如果需要隐藏某个标的，可以在标的编辑页面找到“发布选项”，将“已发表”选项取消，这样就可以实现以上需求
