### ISSUE TITLE
因身份认证失败导致用户无法在宜宾开户处理

### ISSUE THREAD

**Issue by zhuxujiee** [jinbeizeng/cowpro#5]
用户实名认证时姓名填写错误，导致在宜宾开户时身份认证失败，并且修改为正确身份信息后仍然无法在宜宾开户。

查询宜宾文档后得知：
用户姓名、身份证号留错了未通过核查怎么办？
请用户在贵平台修正姓名、身份证号后平台换一个用户ID重新调用我行U00001接口新开一个户，我行会重新发起联网核查。
在生产环境，平台调用U00001开户后，我行会将姓名和身份证号信息送到人行进行联网核查，但人行核查时间较长，该过程不是同步的，无法实时获知核查是否通过。接下来平台引导用户到H5页面设置存管账户密码时我行会获取人行的核查结果，如果核查未通过则不允许留密也无法做后续交易。也就是说，U00001实际是“预开户”，调用U00001成功不代表开户成功，直到成功完成留密和绑卡才算是有效的存管户。

修改方案设想：
如用户ID为12345，开户时收到宜宾返回身份认证失败信息后，系统自动将用户用户ID修改为100012345，这样用户可以重新去宜宾开户，如果该用户第二次身份信息依然输入有误，则ID再次改为110012345，这样用户可以再次去宜宾开户。

以上只是设想具体方案还需讨论。
@jinbeizeng/team

**Comment by DostarQ** [comment]
用户实名认证时姓名填写错误，导致在宜宾开户时身份认证失败，通过后台管理员提交用户ID进行重新关联。

**Comment by DostarQ** [comment]
新方案：用户实名认证时姓名填写错误，导致在宜宾开户时身份认证失败。管理员在后台通过提交用户ID删除用户的资料。用户可以重新注册账号，进行关联宜宾。
